import React from 'react';
import { AlertTriangle, Info, CheckCircle2, ShieldAlert } from 'lucide-react';

interface BoundingBox {
  xMin: number;
  yMin: number;
  xMax: number;
  yMax: number;
}

interface Defect {
  type: string;
  diseaseName: string;
  confidence: number;
  areaPercentage: number;
  severity: string;
  symptoms: string[];
  causes: string[];
  prevention: string[];
  treatment: string;
  storageAdvice: string;
  bbox: BoundingBox;
}

interface DetectionResultProps {
  imageUrl: string; // The annotated image returned from backend
  defects: Defect[];
}

export const DetectionResult: React.FC<DetectionResultProps> = ({ imageUrl, defects }) => {
  if (!defects || defects.length === 0) {
    return (
      <div className="w-full max-w-5xl mx-auto bg-white dark:bg-slate-900 rounded-3xl shadow-xl overflow-hidden border border-emerald-100 dark:border-emerald-900">
        <div className="p-8 text-center">
          <CheckCircle2 className="w-16 h-16 text-emerald-500 mx-auto mb-4" />
          <h2 className="text-3xl font-bold text-slate-800 dark:text-white">Healthy Onion</h2>
          <p className="text-slate-500 mt-2">No diseases or defects detected by the AI model.</p>
        </div>
      </div>
    );
  }

  // Use the primary defect (highest confidence/severity) for the hero section
  const primaryDefect = defects.reduce((prev, current) => 
    (prev.confidence > current.confidence) ? prev : current
  );

  const getSeverityColor = (severity: string) => {
    switch (severity.toUpperCase()) {
      case 'CRITICAL': return 'text-red-600 bg-red-100 dark:bg-red-900/30';
      case 'HIGH': return 'text-orange-600 bg-orange-100 dark:bg-orange-900/30';
      case 'MODERATE': return 'text-yellow-600 bg-yellow-100 dark:bg-yellow-900/30';
      default: return 'text-emerald-600 bg-emerald-100 dark:bg-emerald-900/30';
    }
  };

  return (
    <div className="w-full max-w-5xl mx-auto bg-white dark:bg-slate-900 rounded-3xl shadow-2xl overflow-hidden border border-slate-200 dark:border-slate-800">
      
      {/* Header */}
      <div className="bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800 px-8 py-6">
        <h2 className="text-2xl font-bold text-slate-800 dark:text-white flex items-center gap-3">
          <ShieldAlert className="w-7 h-7 text-indigo-500" />
          Onion Health Analysis
        </h2>
      </div>

      <div className="p-8">
        <div className="flex flex-col lg:flex-row gap-10">
          
          {/* Left Column: Image Area */}
          <div className="w-full lg:w-1/2">
            <div className="relative rounded-2xl overflow-hidden shadow-inner bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800">
              <img 
                src={imageUrl} 
                alt="Detected Onion" 
                className="w-full h-auto object-contain max-h-[500px]"
              />
            </div>
            <p className="text-xs text-center text-slate-400 mt-3 flex items-center justify-center gap-1">
              <Info className="w-3 h-3" />
              Bounding boxes and grades are auto-generated by YOLO11n
            </p>
          </div>

          {/* Right Column: Hero Stats (Phase 10 & 11 & 12) */}
          <div className="w-full lg:w-1/2 flex flex-col justify-center space-y-8">
            
            {/* Disease Detected */}
            <div>
              <p className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">Disease Detected</p>
              <div className="flex items-center gap-3">
                <div className="w-4 h-4 rounded-full bg-red-500 animate-pulse"></div>
                <h3 className="text-3xl font-extrabold text-slate-800 dark:text-white tracking-tight">
                  {primaryDefect.type.replace('_', ' ')}
                </h3>
              </div>
            </div>

            {/* Confidence Bar */}
            <div>
              <div className="flex justify-between items-end mb-2">
                <p className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Confidence</p>
                <span className="text-2xl font-bold text-indigo-600 dark:text-indigo-400">
                  {Math.round(primaryDefect.confidence * 100)}%
                </span>
              </div>
              <div className="w-full h-3 bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-indigo-500 rounded-full transition-all duration-1000 ease-out"
                  style={{ width: `${Math.round(primaryDefect.confidence * 100)}%` }}
                ></div>
              </div>
            </div>

            {/* Severity & Affected Area */}
            <div className="grid grid-cols-2 gap-6">
              <div className="bg-slate-50 dark:bg-slate-800/40 p-5 rounded-2xl border border-slate-100 dark:border-slate-800">
                <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">Severity</p>
                <span className={`inline-block px-3 py-1 rounded-md text-sm font-bold tracking-widest ${getSeverityColor(primaryDefect.severity)}`}>
                  {primaryDefect.severity}
                </span>
                <p className="text-[10px] text-slate-400 mt-2">*Based on agronomic model heuristic</p>
              </div>

              <div className="bg-slate-50 dark:bg-slate-800/40 p-5 rounded-2xl border border-slate-100 dark:border-slate-800">
                <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">Affected Area</p>
                <p className="text-2xl font-bold text-slate-800 dark:text-white">
                  {primaryDefect.areaPercentage.toFixed(1)}%
                </p>
              </div>
            </div>

          </div>
        </div>
      </div>

      {/* Disease Information Module (Phase 13) */}
      <div className="border-t border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/30">
        <div className="p-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          
          {/* Symptoms */}
          <div>
            <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider mb-3 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-purple-500"></span>
              Symptoms
            </h4>
            <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-400">
              {primaryDefect.symptoms.map((symptom, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-purple-500 mt-0.5">•</span>
                  {symptom}
                </li>
              ))}
            </ul>
          </div>

          {/* Causes */}
          <div>
             <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider mb-3 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-orange-500"></span>
              Possible Causes
            </h4>
            <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-400">
              {primaryDefect.causes.map((cause, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-orange-500 mt-0.5">•</span>
                  {cause}
                </li>
              ))}
            </ul>
          </div>

          {/* Prevention */}
          <div>
            <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider mb-3 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-blue-500"></span>
              Prevention
            </h4>
            <ul className="space-y-2 text-sm text-slate-600 dark:text-slate-400">
              {primaryDefect.prevention.map((prev, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-blue-500 mt-0.5">•</span>
                  {prev}
                </li>
              ))}
            </ul>
          </div>

          {/* Treatment & Recommendation */}
          <div>
            <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider mb-3 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
              Recommendation
            </h4>
            <div className="text-sm text-slate-600 dark:text-slate-400 space-y-3">
              <p>{primaryDefect.treatment}</p>
              <div className="flex items-start gap-2 p-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg">
                <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                <p className="text-xs text-amber-800 dark:text-amber-400">
                  Always consult with a certified agronomist before applying chemical treatments.
                </p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};
